### ISSUE TITLE
uff to trt engine error

### ISSUE THREAD

**Issue by wangzilu** [guilherme-pombo/Resnet_Tensorrt#1]
[TensorRT] ERROR: runtime.cpp (16) - Cuda Error in allocate: 2
  File "/usr/lib/python3.5/dist-packages/tensorrt/utils/_utils.py", line 283, in uff_to_trt_engine
    assert(engine)
[TensorRT] ERROR: runtime.cpp (16) - Cuda Error in allocate: 2
[TensorRT] ERROR: Failed to create engine
Traceback (most recent call last):
  File "/usr/lib/python3.5/dist-packages/tensorrt/utils/_utils.py", line 283, in uff_to_trt_engine
    assert(engine)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wang/Downloads/Resnet_Tensorrt-master/tensorrt_wrapper.py", line 148, in <module>
    model_output_name=model_output_name)
  File "/home/wang/Downloads/Resnet_Tensorrt-master/tensorrt_wrapper.py", line 40, in __init__
    self.context = self.parse_uff_model(uff_path=uff_path)
  File "/home/wang/Downloads/Resnet_Tensorrt-master/tensorrt_wrapper.py", line 60, in parse_uff_model
    datatype=TRT_DATATYPE)
  File "/usr/lib/python3.5/dist-packages/tensorrt/utils/_utils.py", line 291, in uff_to_trt_engine
    raise AssertionError('UFF parsing failed on line {} in statement {}'.format(line, text))
AssertionError: UFF parsing failed on line 283 in statement assert(engine)

Process finished with exit code 1

**Comment by wangzilu** [comment]
@guilherme-pombo and could you please post your environment such as keras\cuda\cudnn\tensorflow etc version.

**Comment by guilherme-pombo** [comment]
Hey, @wangzilu I'll look at this over the weekend and get back to you

**Comment by wangzilu** [comment]
@guilherme-pombo thank you, the error will occur at the step  
engine = trt.utils.uff_to_trt_engine(logger=trt_logger,
                                             stream=uff_model,
                                             parser=parser,
                                             max_batch_size=MAX_BATCH_SIZE,
                                             max_workspace_size=MAX_WORKSPACE_SIZE,
                                             datatype=TRT_DATATYPE)

**Comment by wangzilu** [comment]
@guilherme-pombo hello, have you got any solution?

**Comment by guilherme-pombo** [comment]
Hey @wangzilu I was trying to fix the issue for the newest TensorRT version and was having the same problem as you.
The solution is at https://github.com/tensorflow/models/tree/master/research/tensorrt I think this updated version might be better than following my out of date code

**Comment by wangzilu** [comment]
@guilherme-pombo Thank you very much for your replying, I haved tried this https://github.com/tensorflow/models/tree/master/research/tensorrt， it is indeed worked on NVIDIA P100, Howerver, there are still several nodes actually not supported by tensorrt. and eventually around 2 times acceleration on P100 using FP16, It should be around 3 times faster if all nodes are supported.
If you have any progress,  Could you share that:)
